// Хронометраж короткого метра
const SHORT_MOVIE_DURATION = 40;

// Данные сетки фильмов (база)
const MOVIE_GRID_NUMBER_BIG = 16;
const MOVIE_GRID_NUMBER_MEDIUM = 8;
const MOVIE_GRID_NUMBER_SMALL = 5;

// Данные сетки фильмов (экстра)
const MOVIE_GRID_NUMBER_BIG_EXTRA = 4;
const MOVIE_GRID_NUMBER_MEDIUM_EXTRA = 3;
const MOVIE_GRID_NUMBER_SMALL_EXTRA = 1;

export {
  SHORT_MOVIE_DURATION,
  MOVIE_GRID_NUMBER_BIG,
  MOVIE_GRID_NUMBER_BIG_EXTRA,
  MOVIE_GRID_NUMBER_MEDIUM,
  MOVIE_GRID_NUMBER_MEDIUM_EXTRA,
  MOVIE_GRID_NUMBER_SMALL,
  MOVIE_GRID_NUMBER_SMALL_EXTRA,
};
